COMMERCE-778 Fix failing test
Was failing with:
DuplicateCommerceAccountException: There is another commerce
	account named 20140

Need to specify a non-default userId to avoid conflicting. Note
that we still have a test failing to clean up after itself.